apiVersion: v1
kind: Service
metadata:
  name: chord
spec:
  selector:
    app.kubernetes.io/name: chord
  clusterIP: None  # headless
  ports:
  - port: 5057
    name: chord
  - port: 5058
    name: uploadserver
---
# TODO: TLS, use NGINX ingress
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: chord
# spec:
#   defaultBackend:
#     service:
#       name: chord
#       port:
#         number:
